version: 2.13.0-{build}

platform:
  - x86_64
#  - x86

configuration: Debug
clone_folder: c:\src\qgis
shallow_clone: true

cache:
  - c:\temp

services: postgresql

skip_commits:
  message: /ci skip/

install:
  - SET PATH=c:\cygwin\bin;%PATH%
  - c:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P flex -P poppler
  - ps: $fonts = (New-Object -ComObject Shell.Application).Namespace(0x14); dir tests/testdata/font/QGIS-Vera/*.ttf | %{ $fonts.CopyHere($_.fullname) }
  - ps: cd ms-windows\osgeo4w
  - perl osgeo4w-appveyor.pl -arch=%platform%
  - cmake --version
  - ctest --version

build_script:
  - touch noclean nobuild noinstall
  - set TESTTARGET=Experimental

test_script:
#  - package-nightly.cmd 2.11.0 %APPVEYOR_BUILD_NUMBER% qgis-dev %platform% %APPVEYOR_REPO_COMMIT:~1,7% appveyor
  - ctest -V -S %APPVEYOR_BUILD_FOLDER%\qgis-test-appveyor.ctest --output-on-failure

deploy: off
