# Conda espec for create a environment for building and running. See INSTALL.md
channels:
  - conda-forge
  - defaults
dependencies:
  - cxx-compiler
  - ccache
  - pkg-config
  - cmake
  - make
  - ninja
  - flex
  - bison
  - cuda-opencl
  - geos
  - qt
  - qca
  - qtwebkit
  - qwt
  - qtkeychain
  - qscintilla2
  - sqlite
  - gdal
  - exiv2
  - pdal
  - mesa-libgl-devel-cos7-x86_64
  - gsl
  - sip
  - libspatialindex
  - pyqt-builder
  - jinja2
  - proj
  - pyproj
  - pygments
  - yaml
  - owslib
  - psycopg2
