name: qgis
version: master
summary: A Free and Open Source Geographic Information System
description: |
  Create, edit, visualise, analyse and publish geospatial information.
  QGIS feels snappy to use and has a pleasing, easy to use graphical user
  interface. It supports a number of raster and vector data formats, with new
  support easily added using the plugin architectur

grade: devel
confinement: strict

apps:
  qgis:
    command: desktop-launch qgis
    plugs: [home, network, unity7]

parts:
  qgis:
    source: .
    plugin: cmake
    after: [desktop-qt5, python-deps]
    build-packages:
      - git
      - build-essential
      - cmake
      - flex
      - bison
      - pyqt5-dev
      - qttools5-dev
      - qtpositioning5-dev
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - libqt5gui5
      - libqt5scripttools5
      - qtscript5-dev
      - libqca-qt5-2-dev
      - grass-dev
      - libgeos-dev
      - libgdal-dev
      - libqt5xmlpatterns5-dev
      - libqt5scintilla2-dev
      - pyqt5.qsci-dev
      - python3-pyqt5.qsci
      - libgsl-dev
      - txt2tags
      - libproj-dev
      - libqwt-qt5-dev
      - libspatialindex-dev
      - pyqt5-dev-tools
      - qttools5-dev-tools
      - qt5-default
      - python3-future
      - python3-pyqt5.qtsql
      - python3-psycopg2
      - coreutils
      - libqt5sql5-sqlite
      - libqca-qt5-2-plugins
      - python3-gdal
      - python3-yaml
    stage-packages:
      - python3-sip
      - python3-sip-dev
  python-deps:
    plugin: nil
    stage-packages:
      - pyqt5-dev
      - python3-pyqt5
      - python3-pyqt5.qsci
