version: '3.1'
services:
  postgres:
    build:
      dockerfile: Dockerfile-postgis
      context: ../../../tests/testdata
    environment:
      - ALLOW_IP_RANGE="172.18.0.0/16"
# The following files are added in Dockerfile-postgis
      - SSL_CERT_FILE=/run/secrets/ssl_cert
      - SSL_KEY_FILE=/run/secrets/ssl_key
      - SSL_CA_FILE=/run/secrets/ssl_ca
    secrets:
      - source: ssl_cert
        target: ssl_cert
      - source: ssl_key
        target: ssl_key
        mode: 0400
      - source: ssl_ca
        target: ssl_ca

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: <YourStrong!Passw0rd>

  qgis-deps:
    tty: true
    image: qgis_image
    volumes:
      - ${TRAVIS_BUILD_DIR}:/root/QGIS
    links:
      - postgres
      - mssql
    env_file:
      - docker-variables.env

secrets:
   ssl_cert:
     file: auth_system/certs_keys/postgres.crt
   ssl_key:
     file: auth_system/certs_keys/postgres.key
   ssl_ca:
     file: auth_system/certs_keys/issuer_ca_cert.pem
